### ISSUE TITLE
Event eloquent.validated* is called two times on $mode->save()

### ISSUE THREAD

**Issue by chrizz1001** [dwightwatson/validating#135] opened 2015-10-14 08:00 UTC
I noticed that the event "eloquent.validated*" is called two times. Anyone knows how to avoid this? 
I use Laravel Extendable package (a bit extended) to write array inputs which works fine. In order to avoid writing those values to the model table I bound a function that removes the "extended" attributes to the "eloquent.validated" event. Sadly validation fails (if it was valid on first run through) because the "to be validated" attributes gets removed on the first loop.

**Comment by dwightwatson** [comment] 2015-10-14 08:54
I haven't been able to replicate this on a clean install. I'm also not familiar with Laravel Extendable, but I can see they're hooking quite deeply into Eloquent and that could be interfering with how events are being fired and handled.

If you're able to replicate this on a clean install with Laravel and you're able to provide the example code it would help to get to the bottom of this. If you find that the issue is caused by some sort of incompatibility with Laravel Extendable it will provide some more clues as to where the problem lies.

**Comment by dwightwatson** [comment] 2015-12-16 23:18
Closing as no new information has been provided.

**Closed by dwightwatson** 2015-12-16 23:18 UTC
